uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - uses: softprops/action-gh-release@v1
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
